# Generated by Django 5.2.4 on 2025-07-18 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_url', models.URLField()),
                ('headquarters_location', models.CharField(max_length=200)),
                ('company_email', models.EmailField(max_length=254)),
                ('number_of_employees', models.CharField(choices=[('<10', 'Less than 10'), ('10-50', '10 to 50'), ('50-150', '50 to 150'), ('150-300', '150 to 300'), ('300-500', '300 to 500'), ('500+', '500+')], max_length=20)),
                ('turnover', models.CharField(choices=[('<1L', 'Less than Rs.1L'), ('1L-10L', 'Rs. 1L to Rs. 10L'), ('10L-50L', 'Rs. 10L to Rs. 50L'), ('50L-100L', 'Rs. 50L to Rs. 100L'), ('100L+', 'More than Rs. 100L')], max_length=20)),
                ('industry_type', models.CharField(choices=[('IT', 'Information Technology'), ('MANUFACTURING', 'Manufacturing'), ('RETAIL', 'Retail'), ('HEALTHCARE', 'Healthcare'), ('FINANCE', 'Finance'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], max_length=20)),
                ('company_description', models.TextField()),
                ('year_established', models.PositiveIntegerField()),
                ('registration_number', models.CharField(max_length=100)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('contact_person_position', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('social_media_linkedin', models.URLField(blank=True)),
                ('social_media_twitter', models.URLField(blank=True)),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
